import type { Exercise, Routine, RoutineItem } from "./model";
const ex = (
  id: string,
  name: string,
  group: string,
  unit: Exercise["unit"] = "reps",
  load: Exercise["load"] = "none",
  notes = "",
): Exercise => ({ id, name, group, unit, load, notes });
export const seedExercises: Exercise[] = [
  ex(
    "mobility",
    "Movilidad articular + banda",
    "Movilidad",
    "minutes",
    "none",
    "5 minutos. En días fríos, obligatoria.",
  ),
  ex("hollow", "Hollow Hold", "Core", "seconds"),
  ex("bolitas", "Bolitas", "Core"),
  ex("archer", "Archer Hold", "Core", "seconds"),
  ex("espinales", "Espinales", "Core"),
  ex("retraction", "Retracción escapular con banda", "Activación"),
  ex(
    "chest-bar",
    "Chest to bar",
    "Tirón",
    "reps",
    "none",
    "Dominadas pronas llevando el pecho a la barra.",
  ),
  ex("chinup", "Dominadas supinas", "Tirón", "reps", "added"),
  ex("row-t", "Remo T · agarre neutro", "Tirón", "reps", "total"),
  ex("hammer", "Curl martillo en polea soga", "Bíceps", "reps", "total"),
  ex(
    "l-up",
    "L-Up",
    "Core",
    "seconds",
    "none",
    "Piernas extendidas o rodillas elevadas.",
  ),
  ex(
    "knee",
    "Elevaciones colgado / Knee to Elbow",
    "Core",
    "reps",
    "none",
    "Se puede utilizar agarre mixto.",
  ),
  ex("plank", "Plancha", "Core", "seconds"),
  ex("cooldown", "Movilidad articular suave", "Movilidad", "check"),
  ex("protraction", "Protracción escapular en plancha alta", "Activación"),
  ex(
    "dips-tempo",
    "Fondos en paralelas · controlados",
    "Empuje",
    "reps",
    "added",
    "Bajá 3 segundos, mantené 2 segundos en profundidad sin relajarte y subí explosivo.",
  ),
  ex("dips", "Fondos en paralelas", "Empuje", "reps", "added"),
  ex("incline", "Press inclinado con barra", "Empuje", "reps", "total"),
  ex("db-press", "Press plano con mancuernas", "Empuje", "reps", "each"),
  ex("diamond", "Flexiones diamante", "Empuje"),
  ex(
    "bulgarian",
    "Sentadilla búlgara con mancuerna",
    "Piernas",
    "reps",
    "each",
    "Repeticiones por lado.",
  ),
  ex("goblet", "Goblet squat", "Piernas", "reps", "total"),
  ex("pullup", "Dominadas pronas a mentón", "Tirón", "reps", "added"),
  ex(
    "pike",
    "Flexiones pino",
    "Empuje",
    "reps",
    "none",
    "Bajada consciente con pausa cerca del suelo y subida explosiva.",
  ),
  ex("curl-z", "Curl de bíceps con barra Z", "Bíceps", "reps", "total"),
  ex(
    "triceps",
    "Extensión de tríceps · polea recta",
    "Tríceps",
    "reps",
    "total",
  ),
  ex("lateral", "Vuelos laterales", "Hombros", "reps", "each"),
  ex("commando-left", "Dominadas comando · lado izquierdo", "Tirón"),
  ex("commando-right", "Dominadas comando · lado derecho", "Tirón"),
  ex("wall-sit", "Sentadilla isométrica", "Piernas", "seconds"),
  ex(
    "lunges",
    "Estocadas atrás alternadas",
    "Piernas",
    "reps",
    "each",
    "Con doble mancuerna. Confirmá si tu objetivo es total o por lado.",
  ),
  ex("jump-squat", "Sentadillas con despegue", "Piernas"),
];
let i = 0;
const it = (
  exerciseId: string,
  sets: number,
  target: string,
  block = "Trabajo principal",
  rest = 90,
  notes = "",
  optional = false,
  circuit = "",
): RoutineItem => ({
  id: "seed-item-" + i++,
  exerciseId,
  sets,
  target,
  block,
  rest,
  notes,
  optional,
  circuit,
});
const warm = () => [
  it("mobility", 1, "5 min", "Entrada en calor", 0),
  ...["hollow", "bolitas", "archer", "espinales"].map((e) =>
    it(
      e,
      2,
      e === "hollow" || e === "archer" ? "10 seg" : "10 reps",
      "Zona media · activación",
      0,
      "",
      false,
      "2 rondas de zona media",
    ),
  ),
];
const close = () => it("cooldown", 1, "Movilidad suave", "Cierre", 0);
export const seedRoutines: Routine[] = [
  {
    id: "routine-pull",
    name: "Jalón + zona media",
    category: "pull",
    notes: "Finalizar con movilidad articular suave.",
    items: [
      ...warm(),
      it("retraction", 2, "15–20 reps", "Activación"),
      it("chest-bar", 2, "1–3 reps"),
      it("chinup", 2, "8–10 reps"),
      it("row-t", 3, "10–12 reps"),
      it("hammer", 2, "10–15 reps", "Opcional", 90, "", true),
      it("l-up", 3, "10–15 seg", "Zona media"),
      it("knee", 4, "8 reps", "Zona media"),
      it("plank", 4, "30 seg", "Zona media", 10),
      close(),
    ],
  },
  {
    id: "routine-push",
    name: "Empuje + piernas",
    category: "push",
    notes: "Finalizar con movilidad articular suave.",
    items: [
      ...warm(),
      it("protraction", 2, "12–15 reps", "Activación"),
      it("dips-tempo", 2, "6–8 reps"),
      it("dips", 2, "8–10 reps"),
      it("incline", 2, "6–8 reps"),
      it("db-press", 2, "10–12 reps"),
      it("diamond", 2, "15–20 reps"),
      it("bulgarian", 2, "8–10 por lado", "Piernas"),
      it("goblet", 3, "10–15 reps", "Piernas"),
      close(),
    ],
  },
  {
    id: "routine-full",
    name: "Full body B",
    category: "full",
    notes: "Finalizar con movilidad articular suave.",
    items: [
      ...warm(),
      it("pullup", 3, "8–10 reps"),
      it("pike", 3, "6–8 reps"),
      it("curl-z", 3, "10–12 reps"),
      it("triceps", 3, "10–15 reps"),
      it("lateral", 3, "10 reps"),
      it("dips", 1, "Máximas reps", "Condicionamiento", 120),
      it(
        "dips",
        2,
        "RIR 3",
        "Condicionamiento",
        120,
        "Referencia original: tres repeticiones menos que en la primera serie. Registrá tu RIR real.",
      ),
      it("commando-left", 1, "Máximas reps", "Condicionamiento", 180),
      it("commando-right", 1, "Máximas reps", "Condicionamiento", 180),
      it("wall-sit", 3, "40 seg", "Piernas"),
      it("lunges", 3, "10–12 reps", "Piernas"),
      it("jump-squat", 3, "15–20 reps", "Piernas"),
      close(),
    ],
  },
];
